apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-java-route
spec:
  host: hello-java-prod.apps.prod-cluster.sandbox503.opentlc.com
  to:
    kind: Service
    name: prod-hello-java-service
  port:
    targetPort: 8080
  tls:
    termination: edge
    